name: Gradle rewriteDryRun
on: [pull_request]

jobs:
  rewriteDryRun:
    if: github.repository == 'opensearch-project/OpenSearch'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        java: [ 21, 24 ]
        os: [ubuntu-latest, windows-latest, macos-latest, macos-13, ubuntu-24.04-arm]
        include:
          - java: 21
            os: 'windows-2025'
            experimental: true
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: gradle
      - name: Run Gradle (rewriteDryRun)
        continue-on-error: ${{ matrix.experimental }}
        shell: bash
        run: ./gradlew rewriteDryRun --build-cache -Dorg.gradle.jvmargs=-Xmx8G
        # https://docs.openrewrite.org/reference/faq#im-getting-javalangoutofmemoryerror-java-heap-space-when-running-openrewrite

